#define ֵ  int
#define  ִ  0
#define  ַ  if
#define ֲ  return
#define ֳ  printf
#define  ꜗ main
#define ꙾  char
#define ꜖  void
#define ֹ  for
#define ּ  sizeof
#define ֻ  malloc
#define ֶ  free
#define ָ  realloc
#define ְ  strcmp
#define ꭫ strtok
#define ﬩ const
#define ῞ while
#define nathan NULL
#define JadoreLesFrites compare꙾s
#define JaimeLesCarottesLeMcdoEtLeChinois addWord
#define JeSuisRougeEtBleuAvecDuFromageQuiSuisJe qsort
#define LAssuranceMaladieEstUneInfirmiereAvecDeLherbe strlen
#define ٴ  typedef
#define ჻ struct
